version: '3.8'
services:
  web:
  api:
    container_name: vwanu_api_stage
    image: vwanu_api:staging-2.0.1
    build:
      context: ./server
      dockerfile: Dockerfile.stage
    ports:
      - '4000:4000'
    environment:
      - PORT=4000
      - PGDATABASE=social_media
      - PGUSER=vwanu
      - PGPASSWORD=123456
      - PGHOST=pg_db
      - REDIS_URL=redis://cache
    depends_on:
      - pg_db
    links:
      - redis
  redis:
    image: redis:6.2-alpine
    container_name: redis
    restart: unless-stopped
    network_mode: bridge
    expose:
      - 6379
  pg_db:
    container_name: pg_db
    image: 'postgres:12'
    ports:
      - '5432:5432'
    restart: always

    environment:
      - POSTGRES_USER=vwanu
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=social_media
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: {}
