version: '3.8'
services:
  web:
    container_name: vwanu_web_stage
    image: vwanu_web:staging-nginx
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=${SERVER_ADDRESS}
    ports:
      - '3000:3000'
    restart: unless-stopped
  api:
    env_file:
      - .env
    container_name: vwanu_api
    image: vwanu_api:0.0.1
    build:
      context: ./server
    ports:
      - '${API_PORT}:${API_PORT}'
    volumes:
      - ./server:/app
    command: ./docker-entrypoint.testing.sh
    depends_on:
      - pg_db

  pg_db:
    container_name: pg_db
    image: 'postgres:12'
    ports:
      - '5432:5432'
    volumes:
      - nps_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_HOST_AUTH_METHOD=${DB_HOST_AUTH_METHOD}
volumes:
  nps_data: {}
