service: vwanu-api-backend
frameworkVersion: '3'
provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 'tag:*'
          Resource: '*'
        - Effect: 'Allow'
          Action:
            - 'logs:*'
          Resource: '*'
        - Effect: Allow
          Action:
            - 'ssm:GetParameter'
            - 'ssm:GetParameters'
          Resource:
            - 'arn:aws:ssm:${self:provider.region}:*:parameter/${sls:stage}/*'
  environment:
    STAGE: ${sls:stage}
    REGION: ${self:provider.region}
    SERVICE_NAME: vwanu-api-backend
    GITHUB_USERNAME: ${env:GITHUB_USERNAME, 'system'}
    DB_HOST: ${self:custom.offlineConfig.${self:custom.isOffline}.databaseHost}
    DB_USERNAME: ${self:custom.offlineConfig.${self:custom.isOffline}.databaseCredentials.username}
    DB_PASSWORD: ${self:custom.offlineConfig.${self:custom.isOffline}.databaseCredentials.password}
    # COGNITO_USER_POOL: ${self:custom.offlineConfig.${self:custom.isOffline}.cognitoUserPool}
    AWS_SDK_JS_SUPPRESS_MAINTENANCE_MODE_MESSAGE: true
    MAX_DISCUSSION_AUDIOS: 5
    MAX_DISCUSSION_IMAGES: 5
    MAX_DISCUSSION_VIDEOS: 2
    MAX_MESSAGE_IMAGES: 5
    MAX_POST_AUDIOS: 5
    MAX_POST_IMAGES: 5
    MAX_POST_VIDEOS: 2
    COGNITO_USER_POOL:
      Ref: CognitoUserPool
    CLIENT_ID:
      Ref: CognitoUserPoolClient
    USER_POOL_ID:
      Ref: CognitoUserPool
    # API_URL: ${self:custom.offlineConfig.${self:custom.isOffline}.
    # CLIENT_ID: ${ssm:/${sls:stage}/clientId}
    # USER_POOL_ID: ${ssm:/${sls:stage}/userPoolId}
    # CLOUDINARY_API_SECRET: ${ssm:/${sls:stage}/CLOUDINARY_API_SECRET} # temporarily until cloudinary is removed
    # CLOUDINARY_API_KEY: ${ssm:/${sls:stage}/CLOUDINARY_API_KEY}
    # CLOUDINARY_CLOUD_NAME: ${ssm:/${sls:stage}/CLOUDINARY_CLOUD_NAME}
   # REDIS_ENDPOINT: ${ssm:/${sls:stage}/redisEndpoint}

plugins:
  - serverless-prune-plugin
  - serverless-lift

custom:
  shortServiceName: vwanu
  ecr:
    repositoryUri: '178092210783.dkr.ecr.us-east-1.amazonaws.com/vwanu/vwanu-api'
    imageTag: ${param:imageTag, "dev-latest"}
  isOffline: ${env:IS_OFFLINE, "false"}
  offlineConfig:
    true:
      databaseHost: ${env:DB_HOST, 'localhost'}
      databaseCredentials:
        username: ${env:DB_USERNAME, 'postgres'}
        password: ${env:DB_PASSWORD, 'postgres'}
      cognitoUserPool: ${env:COGNITO_USER_POOL, ''}
      apiUrl: ${env:API_URL, 'http://localhost:3000'}
    false:
      databaseHost:
        Fn::GetAtt:
          - VwanuDb
          - Endpoint.Address
      databaseCredentials:
        username: ${env:DB_USERNAME, 'postgres'}
        password: ${env:DB_PASSWORD, 'postgres'}
      cognitoUserPool:
        Ref: CognitoUserPool
      apiUrl: https://api.wadsonvaval.click
  databaseMultiAz:
    prod: true
    staging: true
    dev: false
    test: false
  adminDomains:
    prod: admin.wadsonvaval.click
    staging: admin-staging.wadsonvaval.click
    dev: admin-dev.wadsonvaval.click
    test: admin-test.wadsonvaval.click
  subjectPrefix:
    prod: ''
    staging: '[STAGING] '
    dev: '[DEV] '
    test: '[TEST] '
  prune:
    automatic: true
    number: 3

resources:
  # Network
  - ${file(resources/network/Network.yml)}

  # Database
  - ${file(resources/database/Database.yml)}

  # Cognito
  - ${file(resources/cognito/UserPool.yml)}

  # ECS
  - ${file(resources/ecs/ecs.yml)}

  # SES
  # - ${file(resources/ses/email.yml)}
