Resources:
  CarCallNotificationTemplate:
    Type: 'AWS::SES::Template'
    Properties:
      Template:
        HtmlPart:
          '<p>A Vwanu Emergency Elevator Comunicator assigned to one of your properties has received an {{mode}} call</p>
          <p>Property: {{propertyName}}</p>
          <p>Car: {{carName}}</p>
          <p>Initiated by User: {{username}}</p>
          <p>Started: {{createdAt}}</p>
          <p>Direct Access Link: <a href="${self:provider.environment.ADMIN_URL}/dashboard/property/{{propertyId}}">Go to {{propertyName}}</p>'
        SubjectPart: '${self:custom.subjectPrefix.${sls:stage}}Vwanu Car Station {{mode}} Call'
        TemplateName: '${self:service}-${sls:stage}-car-call-notification'
        TextPart: 'A Vwanu Emergency Elevator Comunicator assigned to one of your properties has received an {{mode}} call. Property: {{propertyName}}, Car: {{carName}}, Initiated by User: {{username}}, Started: {{createdAt}}'
  CarOfflineNotificationTemplate:
    Type: 'AWS::SES::Template'
    Properties:
      Template:
        HtmlPart:
          '<p>A Vwanu Emergency Elevator Comunicator assigned to one of your properties has been offline for more than {{offlineThresholdMinutes}} minutes.</p>
          <p>Property: {{propertyName}}</p>
          <p>Car: {{carName}}</p>
          <p>Time: {{createdAt}}</p>
          <p>Direct Access Link: <a href="${self:provider.environment.ADMIN_URL}/dashboard/property/{{propertyId}}">Go to {{propertyName}}</p>'
        SubjectPart: '${self:custom.subjectPrefix.${sls:stage}}Vwanu device offline: {{propertyName}} - {{carName}}'
        TemplateName: '${self:service}-${sls:stage}-car-offline-notification'
        TextPart: 'A Vwanu Emergency Elevator Comunicator assigned to one of your properties has been offline for more than {{offlineThresholdMinutes}} minutes.. Property: {{propertyName}}, Car: {{carName}}, Time: {{createdAt}}'
  CallNotAnsweredNotificationTemplate:
    Type: 'AWS::SES::Template'
    Properties:
      Template:
        HtmlPart: '<p>A Vwanu Emergency Call went unanswered.</p>
          <p>Property: {{propertyName}}</p>
          <p>Car: {{carName}}</p>'
        SubjectPart: '${self:custom.subjectPrefix.${sls:stage}}Vwanu call went unanswered: {{propertyName}} - {{carName}}'
        TemplateName: '${self:service}-${sls:stage}-call-not-answered-notification'
        TextPart: 'A Vwanu Emergency Elevator Call went unanswered.. Property: {{propertyName}}, Car: {{carName}}'
