Resources:
  BANNED:
    Type: 'AWS::SES::Template'
    Properties:
      Template:
        HtmlPart:
          '<p>A Vwanu Emergency Elevator Comunicator assigned to one of your properties has received an {{mode}} call</p>
          <p>Property: {{propertyName}}</p>
          <p>Car: {{carName}}</p>
          <p>Initiated by User: {{username}}</p>
          <p>Started: {{createdAt}}</p>
          <p>Direct Access Link: <a href="gogle.com/dashboard/property/{{propertyId}}">Go to {{propertyName}}</p>'
        SubjectPart: '${self:custom.subjectPrefix.${sls:stage}}Vwanu Car Station {{mode}} Call'
        TemplateName: '${self:service}-${sls:stage}-car-call-notification'
        TextPart: 'A Vwanu Emergency Elevator Comunicator assigned to one of your properties has received an {{mode}} call. Property: {{propertyName}}, Car: {{carName}}, Initiated by User: {{username}}, Started: {{createdAt}}'
