Resources:
  VwanuDb:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      DBInstanceIdentifier: vwanu-api-backend-${sls:stage}-new-23
      DBInstanceClass: db.t4g.small
      Engine: postgres
      EngineVersion: 13
      AllocatedStorage: 20
      MaxAllocatedStorage: 100
      StorageType: gp3
      BackupRetentionPeriod: 30
      MultiAZ: ${self:custom.databaseMultiAz.${sls:stage}}
      EnablePerformanceInsights: true
      PubliclyAccessible: true
      DeletionProtection: false
      MasterUsername: ${self:provider.environment.DB_USERNAME}
      MasterUserPassword: ${self:provider.environment.DB_PASSWORD}
