Resources:
  VwanuDb:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      DBInstanceIdentifier: vwanu-api-backend-${sls:stage}
      DBName: vwanu
      DBInstanceClass: ${self:custom.dbInstanceClass.${sls:stage}}
      Engine: postgres
      EngineVersion: '16.6'
      AllocatedStorage: 20
      MaxAllocatedStorage: ${self:custom.dbMaxStorage.${sls:stage}}
      StorageType: gp3
      BackupRetentionPeriod: ${self:custom.dbBackupRetention.${sls:stage}}
      MultiAZ: ${self:custom.databaseMultiAz.${sls:stage}}
      EnablePerformanceInsights: ${self:custom.dbPerformanceInsights.${sls:stage}}
      PubliclyAccessible: true
      DeletionProtection: false
      MasterUsername: ${self:provider.environment.DB_USERNAME}
      MasterUserPassword: ${self:provider.environment.DB_PASSWORD}
