- Name: STAGE
  Value: ${self:provider.environment.STAGE}
- Name: REGION
  Value: ${self:provider.environment.REGION}
- Name: SERVICE_NAME
  Value: ${self:provider.environment.SERVICE_NAME}
- Name: ZERO_TIER_API_TOKEN
  Value: ${self:provider.environment.ZERO_TIER_API_TOKEN}
- Name: ZERO_TIER_NETWORK_ID
  Value: ${self:provider.environment.ZERO_TIER_NETWORK_ID}
- Name: ADMIN_URL
  Value: ${self:provider.environment.ADMIN_URL}
- Name: DB_HOST
  Value: ${self:provider.environment.DB_HOST}
- Name: DB_USERNAME
  Value: ${self:provider.environment.DB_USERNAME}
- Name: DB_PASSWORD
  Value: ${self:provider.environment.DB_PASSWORD}
- Name: COGNITO_USER_POOL
  Value: ${self:provider.environment.COGNITO_USER_POOL}
- Name: SQS_CALL_QUEUE_URL
  Value: ${self:provider.environment.SQS_CALL_QUEUE_URL}
- Name: SENTRY_DSN
  Value: ${self:provider.environment.SENTRY_DSN}
- Name: API_URL
  Value: ${self:provider.environment.API_URL}
- Name: APPSYNC_URL
  Value: ${self:provider.environment.APPSYNC_URL}
- Name: APPSYNC_API_KEY
  Value: ${self:provider.environment.APPSYNC_API_KEY}
- Name: SENTRY_RELEASE
  Value: ${self:provider.environment.SENTRY_RELEASE}
- Name: AWS_SDK_JS_SUPPRESS_MAINTENANCE_MODE_MESSAGE
  Value: ${self:provider.environment.AWS_SDK_JS_SUPPRESS_MAINTENANCE_MODE_MESSAGE}
- Name: REDIS_ENDPOINT
  Value: ${self:provider.environment.REDIS_ENDPOINT}
