- Name: STAGE
  Value: ${self:provider.environment.STAGE}
- Name: REGION
  Value: ${self:provider.environment.REGION}
- Name: SERVICE_NAME
  Value: ${self:provider.environment.SERVICE_NAME}
- Name: GITHUB_USERNAME
  Value: ${self:provider.environment.GITHUB_USERNAME}
- Name: DB_HOST
  Value: ${self:provider.environment.DB_HOST}
- Name: DB_USERNAME
  Value: ${self:provider.environment.DB_USERNAME}
- Name: DB_PASSWORD
  Value: ${self:provider.environment.DB_PASSWORD}
- Name: COGNITO_USER_POOL
  Value: ${self:provider.environment.COGNITO_USER_POOL}
- Name: API_URL
  Value: ${self:provider.environment.API_URL}
- Name: AWS_SDK_JS_SUPPRESS_MAINTENANCE_MODE_MESSAGE
  Value: ${self:provider.environment.AWS_SDK_JS_SUPPRESS_MAINTENANCE_MODE_MESSAGE}
- Name: CLIENT_ID
  Value: ${self:provider.environment.CLIENT_ID}
- Name: USER_POOL_ID
  Value: ${self:provider.environment.USER_POOL_ID}
- Name: CLOUDINARY_API_SECRET
  Value: ${self:provider.environment.CLOUDINARY_API_SECRET}
- Name: CLOUDINARY_API_KEY
  Value: ${self:provider.environment.CLOUDINARY_API_KEY}
- Name: CLOUDINARY_CLOUD_NAME
  Value: ${self:provider.environment.CLOUDINARY_CLOUD_NAME}
- Name: MAX_POST_VIDEOS
  Value: ${self:provider.environment.MAX_POST_VIDEOS}
- Name: MAX_POST_AUDIOS
  Value: ${self:provider.environment.MAX_POST_AUDIOS}
- Name: MAX_POST_IMAGES
  Value: ${self:provider.environment.MAX_POST_IMAGES}
- Name: MAX_MESSAGE_IMAGES
  Value: ${self:provider.environment.MAX_MESSAGE_IMAGES}
- Name: MAX_DISCUSSION_VIDEOS
  Value: ${self:provider.environment.MAX_DISCUSSION_VIDEOS}
- Name: MAX_DISCUSSION_AUDIOS
  Value: ${self:provider.environment.MAX_DISCUSSION_AUDIOS}
- Name: MAX_DISCUSSION_IMAGES
  Value: ${self:provider.environment.MAX_DISCUSSION_IMAGES}
