version: '3.8'

services:
  app:
    container_name: vwanu_dev_container
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
      - ~/.gitconfig:/home/node/.gitconfig
    environment:
      - NODE_ENV=development
      - PORT=4000
      - PGDATABASE=social_media
      - PGUSER=vwanu
      - PGPASSWORD=123456
      - PGHOST=postgres
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - postgres
      - redis
    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function
    network_mode: service:postgres
    # Use the sleep command to keep the container running
    command: sleep infinity
    user: node
    
  postgres:
    container_name: postgres
    image: postgres:12
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=vwanu
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=social_media
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
    
  redis:
    container_name: redis
    image: redis:alpine
    restart: unless-stopped
    ports:
      - 6379:6379

volumes:
  postgres-data:
